import type { Metadata } from "next";
import { Inter } from "next/font/google";
import Header from './components/header';
import {Footer} from './components/footer';
import {aboutMeData, pages, contactMeLinks} from './data/data';
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <Header name={aboutMeData.name} pages={pages} /> 
        className={inter.className}{children}
        <Footer contactMeLinks={}/>
      </body>
    </html>
  );
}
